### ISSUE TITLE
Cannot compile on mingw or cygwin

### ISSUE THREAD

**Issue by affggh** [svoboda18/magiskboot#1]
I have already have clang llvm zlib-devel etc package,
![image](https://user-images.githubusercontent.com/46290091/200521226-1956622c-6f46-4e0c-a0b1-7f3b474a5a9e.png)
Maybe you can see this [Patch](https://github.com/xiaoxindada/magiskboot_ndk_on_linux/blob/cygwin/patches/public/0001-Add-cygwin-changes.patch)

Really great port work !

**Comment by svoboda18** [comment]
it should be fixed after [9d4c8f](https://github.com/svoboda18/magiskboot/commit/9d4c8f2220d470f344e9a23e4402f493972efe02).

Consider using MSYS2 CLANG64 LLVM 15 as it is up-to-date and addressed lot of bugs.

That patch you have referenced is off-topic since it is for CYGWIN and still based on CYGWIN ported POSIX functions.

**Comment by svoboda18** [comment]
d_namlen member exists only in MINGW dirnet struct.
